F1 = SquareSolver
F2 = Squaretester
F3 = SquareProject

all: $(F3)

$(F3): $(F1).o $(F2).o $(F3).o
	g++ $(F1).o $(F2).o $(F3).o -o $(F3)

$(F1).o: $(F1).cpp
	g++ -c $(F1).cpp

$(F2).o: $(F2).cpp
	g++ -c $(F2).cpp

$(F3).o: $(F3).cpp
	g++ -c $(F3).cpp

clean:
	rm -rf *.o $(F3)